name: Linux

on:
  push:
    paths:
      - "**.zig"
  pull_request:
    paths:
      - "**.zig"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Setup Gyro
        uses: mattnite/setup-gyro@v1.0.1

      - name: Test
        run: gyro build test

      - name: Example (Get)
        working_directory: examples
        run: gyro build get

      - name: Example (Post)
        working_directory: examples
        run: gyro build get